gretchen:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10  

  head_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - pan_joint
      - tilt_joint

    gains: # Required because we're controlling an effort interface
      pan_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
      tilt_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}